#!/bin/bash

##############################################################################
# ts-tags - Lists tags for a file as found in 
#           its metadata JSON file (./.ts/$1.json).
#         - Params: filename
#         - stdout: tags, one per line
##############################################################################


if [ "$#" -eq "1" ]
then
	python -m mytags.MyTagsUtils tags "$@"
else 
	python -m mytags.MyTagsUtils "$@"

fi
