#!/bin/bash

#!/usr/bin/python
#import mytags.MyTagsUtils as mt
#mt.printTags(my.getTags(


##############################################################################
# ts-tags - Lists tags for a file as found in 
#           its metadata JSON file (./.ts/$1.json).
#         - Params: filename
#         - stdout: tags, one per line
##############################################################################

#metafile=`dirname "$1"`/.ts/`basename "$1"`.json


#if [[ -e "$metafile" ]]; then
#	jq -r -M '.tags[] | .title' "$metafile" 2>/dev/null
#fi
if [ ! -z "$1" ]
then
	python -m mytags.MyTagsUtils tags "$1"
else
	#python -m mytags.MyTagsUtils
	echo "Missing argument: [filename]"
fi
